# Generated by Django 5.0.7 on 2024-08-07 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_client_order_basket_productamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
