# Generated by Django 5.0.7 on 2024-08-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_client_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_email',
        ),
    ]
