# Generated by Django 5.0.7 on 2024-08-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_client_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_email',
            field=models.EmailField(default='none', max_length=254),
        ),
    ]
