# Generated by Django 5.0.7 on 2024-08-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_basket_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='basket',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='basket',
            old_name='order_id',
            new_name='order',
        ),
    ]
