# Generated by Django 5.1 on 2024-08-10 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_order_username_cart_delete_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='item_amount',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='productamount',
            old_name='item_amount',
            new_name='product_amount',
        ),
        migrations.RenameField(
            model_name='productamount',
            old_name='item_id',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.cart'),
            preserve_default=False,
        ),
    ]
