# Generated by Django 5.1 on 2024-08-10 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_order_cart_cart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productamount',
            name='product_id',
        ),
        migrations.AddField(
            model_name='productamount',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.product'),
        ),
    ]
